eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
    
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.150:3306/example
    username: dbuser
    password: easypay@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
